connection:
  host: localhost
  port: 8000

# connection:
#   host: controller.example.com
#   port: 443
#   ip_version: 4
#   secure: true

devices:
  Controller (1):
    group_id: test
    allowed_events:
      - BTN_DPAD_UP
      - BTN_DPAD_DOWN
      - BTN_DPAD_LEFT
      - BTN_DPAD_RIGHT
      - BTN_A
      - BTN_B
      - BTN_X
      - BTN_Y
      - BTN_TL
      - BTN_TR
      - BTN_TL2
      - BTN_TR2
      - BTN_START
      - BTN_SELECT
      - BTN_THUMBL
      - BTN_THUMBR
    presets:
      - default
      - alt
    device_type: uinput
    uinput_name: Generic Device
    bustype: 0
    vendor: 0
    product: 0
    version: 0
  Controller (2):
    group_id: test
    allowed_events:
      - BTN_DPAD_UP
      - BTN_DPAD_DOWN
      - BTN_DPAD_LEFT
      - BTN_DPAD_RIGHT
      - BTN_A
      - BTN_B
      - BTN_X
      - BTN_Y
      - BTN_TL
      - BTN_TR
      - BTN_TL2
      - BTN_TR2
      - BTN_START
      - BTN_SELECT
      - BTN_THUMBL
      - BTN_THUMBR
    presets:
      - default
      - alt
    device_type: uinput
    uinput_name: Generic Device
    bustype: 0
    vendor: 0
    product: 0
    version: 0
  Controller (3):
    group_id: test
    allowed_events:
      - BTN_DPAD_UP
      - BTN_DPAD_DOWN
      - BTN_DPAD_LEFT
      - BTN_DPAD_RIGHT
      - BTN_A
      - BTN_B
      - BTN_X
      - BTN_Y
      - BTN_TL
      - BTN_TR
      - BTN_TL2
      - BTN_TR2
      - BTN_START
      - BTN_SELECT
      - BTN_THUMBL
      - BTN_THUMBR
    presets:
      - default
      - alt
    device_type: uinput
    uinput_name: Generic Device
    bustype: 0
    vendor: 0
    product: 0
    version: 0
  Controller (4):
    group_id: test
    allowed_events:
      - BTN_DPAD_UP
      - BTN_DPAD_DOWN
      - BTN_DPAD_LEFT
      - BTN_DPAD_RIGHT
      - BTN_A
      - BTN_B
      - BTN_X
      - BTN_Y
      - BTN_TL
      - BTN_TR
      - BTN_TL2
      - BTN_TR2
      - BTN_START
      - BTN_SELECT
      - BTN_THUMBL
      - BTN_THUMBR
    presets:
      - default
      - alt
    device_type: uinput
    uinput_name: Generic Device
    bustype: 0
    vendor: 0
    product: 0
    version: 0

keybind_preset_library:
  default:
    - [KeyW, BTN_DPAD_UP]
    - [KeyA, BTN_DPAD_LEFT]
    - [KeyS, BTN_DPAD_DOWN]
    - [KeyD, BTN_DPAD_RIGHT]
    - [KeyE, BTN_A]
    - [KeyQ, BTN_B]
    - [KeyX, BTN_X]
    - [KeyY, BTN_Y]
    - [Tab, BTN_TL]
    - [KeyR, BTN_TR]
    - [Escape, BTN_START]
    - [Space, BTN_A]
    - [KeyZ, BTN_Y]
    - [KeyF, BTN_Y]
  alt:
    - [ArrowUp, BTN_DPAD_UP]
    - [ArrowDown, BTN_DPAD_DOWN]
    - [ArrowLeft, BTN_DPAD_LEFT]
    - [ArrowRight, BTN_DPAD_RIGHT]
    - [Enter, BTN_START]
