services:
  server:
    container_name: dvc-server
    build:
      dockerfile: Dockerfile.python
    volumes:
      - ./src/server:/app
    command: ["uvicorn", "server:app", "--host", "0.0.0.0"]
    restart: unless-stopped

  web-build-runner:
    container_name: dvc-web-build-runner
    image: node:24
    working_dir: /app
    command: ["sh", "-c", "npm install && npm run build --"]
    volumes:
      - ./src/web:/app

  nginx:
    container_name: dvc-nginx
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/web/dist:/usr/share/nginx/html
    networks:
      - default
      - local

networks:
  local:
    name: local
    external: true
  default:
    name: dvc-internal
    external: false
