services:
  server:
    container_name: dvc-server
    build:
      dockerfile: Dockerfile.python
    volumes:
      - ./src/server:/app
    restart: unless-stopped
    networks:
      - internal

  # web-build-runner:
  #   container_name: dvc-web-build-runner
  #   image: node:24
  #   working_dir: /app
  #   command: ["sh", "build.sh"]
  #   volumes:
  #     - ./src/web:/app
  #   networks:
  #     - internal

  web:
    container_name: dvc-web
    image: node:24
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
    volumes:
      - ./src/web:/app
    restart: unless-stopped
    networks:
      - internal

  nginx:
    container_name: dvc-nginx
    image: nginx:latest
    ports:
      - 8000:80
    restart: unless-stopped
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal

networks:
  internal:
    name: dvc-internal
    external: false
